using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Linq;
using System.ComponentModel.Design;
using System.Security.Cryptography;
using ProjectEulerSharp.Sequences;
using System.Collections.Generic;

namespace ProjectEulerSharp.Page01
{
    /******************************************************************************
     * URL: http://projecteuler.net/problem=044
     * Title: Pentagon numbers
     * Pentagonal numbers are generated by the formula, P(n)=n(3n−1)/2. The first ten 
     * pentagonal numbers are:
     * 
     * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
     * 
     * It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their difference, 
     * 70 − 22 = 48, is not pentagonal.
     * 
     * Find the pair of pentagonal numbers, P(j) and P(k), for which their sum and 
     * difference are pentagonal and D = |P(k) − P(j)| is minimised; what is the value of D?
     ******************************************************************************/
    [TestClass]
    public class Problem044 : ProblemBase
    {
        protected override long SolutionImplementation()
        {
            Assert.Inconclusive("Test is not yet implemented.");
            return -1;
        }
    }
}